### ISSUE TITLE
Standalone usage / Testing

### ISSUE THREAD

**Issue by pmelab** [jfcherng/copilot-node-server#23]
Hi! I'm trying to get this to work with [Helix](https://helix-editor.com/):

```toml
[language-server.copilot]
command = "copilot-node-server"
args = ["--stdio"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "eslint", "copilot"]
```

According to the logs, everything is fine, but I simply get no autocomplete results from copilot. Does anybody know if this is something that _should_ work? Or are there any tips on how to test the server on it's own to isolate the point of failure?
